### ISSUE TITLE
blueish tint added to openCV images.

### ISSUE THREAD

**Issue by daljeet-hcl** [jremmons/pyfakewebcam#2]
I tried using your pyfakewebCam. Here is my sample code.
https://gist.github.com/daljeet-hcl/9eee797715ac504e1694846d65eb3f78

your software adds a bluish tint to the images produced, can you help to fix it and restore original colors. I am a newbie to python and C. 

Regards
Daljeet Singh

**Comment by jremmons** [comment]
OpenCV stores pixels in blue-green-red (BGR) order by default. My fake webcam library expects the frames to be in [red-green-blue (RGB) order](https://github.com/jremmons/pyfakewebcam/blob/master/pyfakewebcam/pyfakewebcam.py#L22) though. I didn't try running your code, but I think adding the line of code below before scheduling the frame will solve the problem:

```
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
```

Let me know if that doesn't solve it for you!

**Comment by daljeet-hcl** [comment]
Great, Thanks a lot jremmons, it did help me solve the problem.
